require.config({paths:{
    "util":"util",
    "base":"base"
}});
require(['story'],function(story){
    story.Renderer.loadCanvas(document.getElementById('stage').getContext("2d"));
    story.addScene();
    story.Renderer.start({FPS:10});
});